### PR TITLE
Install README, ChangeLog, GeoIP.conf.default etc into docdir (issue #26...

### PR DESCRIPTION
**Pull request by pprindeville**
Fix for issue #26

### CODE REVIEW

**Comment by oschwald** [comment]
Thanks. Although I agree the current GeoIP.conf.default is more documentation than a usable conf file, I wonder if it would be preferable if we pre-populated it with the values for GeoLite downloads, making it usable as is.

**Comment by pprindeville** [comment]
Then that would be installed as /etc/GeoIP.conf instead, right?

**Comment by oschwald** [comment]
Yeah, it would be installed to the sysconf directory.

**Comment by pprindeville** [comment]
Okay, so what's the appropriate fix then?

**Comment by oschwald** [comment]
If you wanted to do it, you could change the default config so that it contains something like this (with the existing comments):

```
LicenseKey 000000000000
UserId 0
ProductIds 506 517 533 GeoLite2-Country GeoLite2-City
```

And then revert the change that installs the config into the docs directory.

**Comment by pprindeville** [comment]
I think packaging both a candidate /etc/GeoIP.conf and a template version of $(docdir)/$(PACKAGE_NAME)/GeoIP.conf.default is the best solution.

**Comment by oschwald** [comment]
Sure, that seems fine.

**Comment by oschwald** [comment]
Sorry, I didn't realize you updated this. I had one comment about the generated config.

**Comment by jippi** [comment]
did this stall?

**Comment by oschwald** [comment]
@jippi, thanks for the reminder. I made the requested changes and merged this from the command line.

**Pull request closed without merging**
